### ISSUE TITLE
Nuxt and TypeScript compatibility issues

### ISSUE THREAD

**Issue by moltar** [nuxt-community/style-resources-module#40] opened 2019-03-22 06:10 UTC
Following up on the #29 issue that is now closed.

There seems to be an issue with `style-resources-module` and TypeScript support.

I have a minimal, reproducible template:

```
vue init scaleleap/nuxt-typescript-template style-resources-module-ts-error
cd style-resources-module-ts-error
npm i
npm run dev
```

Errors out with:

```
 ERROR  Failed to compile with 1 errors                                                                        friendly-errors 13:02:30


 ERROR  in ./pages/index.vue?vue&type=style&index=0&lang=scss&                                                 friendly-errors 13:02:30

Module build failed (from ./node_modules/sass-loader/lib/loader.js):                                           friendly-errors 13:02:30

  background-color: $body-bg;
                   ^
      Undefined variable: "$body-bg".
      in /private/tmp/your-project-name/pages/index.vue (line 14, column 21)
                                                                                                               friendly-errors 13:02:30
 @ ./node_modules/vue-style-loader??ref--9-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--9-oneOf-1-2!./node_modules/sass-loader/lib/loader.js??ref--9-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=style&index=0&lang=scss& 4:14-369 14:3-18:5 15:22-377
 @ ./pages/index.vue?vue&type=style&index=0&lang=scss&
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js
```

----

 Template source: https://github.com/ScaleLeap/nuxt-typescript-template

----

Thank you for your attention.

**Comment by moltar** [comment] 2019-04-16 09:29
Moved broken example to a branch, so I can use master: https://github.com/ScaleLeap/nuxt-typescript-template/tree/style-resources-breakage

Not sure how to use a branch with `vue init` otherwise I'd edit my original post.

**Comment by envision** [comment] 2019-07-09 10:42
When will this be fixed? I tried this module out already in March, and deemed it unusable with TypeScript + Nuxt project because of this bug...

With Vue 3 approaching, having TypeScript supported should get more priority.

**Comment by manniL** [comment] 2019-08-07 14:24
Is this fixed with v1?

**Comment by davision** [comment] 2019-09-05 13:39
Hmm still not fixed. Is there any work around maybe?

**Comment by crhistianramirez** [comment] 2019-11-11 04:20
@manniL I can confirm this is still a bug with version 1.0.0

**Comment by lukas-martys** [comment] 2019-12-11 19:33
Not an ideal solution but the way I am currently running this is via official nuxt typescript runtime.

**Comment by lupas** [comment] 2020-03-03 09:27
@lukas-martys 
I'm running it with nuxt-ts too but I am getting the error nevertheless. Does it indeed work for you?

@manniL 
Any way around it yet?

**Comment by kn0wn** [comment] 2020-03-10 14:50
Just adding my two cents; adding `@nuxt/typescript-runtime` and using `nuxt-ts` like @lukas-martys said works for me. I also tried a fresh install of my node modules and removed package-lock.

**Comment by crhistianramirez** [comment] 2020-05-16 21:31
@lukas-martys  @kn0wn 

That workaround doesn't seem to be working for me. I have a minimal reproducible example [here](https://github.com/crhistianramirez/ts-style-repro). Can you spot anything?

Steps to repro:
1. Created app with `npx create-nuxt-app my-app`, all defaults except the following
    - Choose a programming language: Typescript
    - Choose the runtime for TypeScript @nuxt/typescript-runtime
2. Install sass: `yarn add --dev sass-loader node-sass`
3. Create _variables.scss in assets with `$brand-primary` variable
4. Add config to nuxt.config.js:
    ```javascript
    styleResources: {
        scss: ['./assets/_variables.scss']
      },
    ```
5. Use variable in a component (in my case pages/index.vue)
6. Try to run app by calling `npm run dev` which in turn calls `nuxt-ts` and get error `SassError: Undefined variable: "$brand-primary".`

**Comment by scellige** [comment] 2020-06-24 11:23
Check for adding `'@nuxtjs/style-resources'` in `modules` section in the `nuxt.config.js` file. It works for me.

**Comment by rchl** [comment] 2021-06-10 22:07
A lot has changed in Nuxt since this was reported and also the repro repos are dead so please report new issue with reproduction steps if this is still a problem.

**Closed by rchl** 2021-06-10 22:07 UTC
Labels: bug
