### ISSUE TITLE
bundle size goes crazy with third party libs

### ISSUE THREAD

**Issue by syffs** [nuxt-community/style-resources-module#42] opened 2019-04-05 10:58 UTC
### Version

0.1.2 (latest)

### Repro

https://codesandbox.io/s/4892kvx3w0

### Steps to reproduce

2 scenarios:

- `extractCSS; true` => getting css files for each page of the size of the whole library (bootstrap here)
- `extractCSS; false` or undefined => getting js files of the size of the whole library (bootstrap here)

hence
1. update `extractCSS` accordingly
2. run `yarn build`

### What is expected ?

the bundle should only include used style references 

### What is actually happening?

the bundle includes the whole library in each page and build may take forever in a real implementation (especially with `extractCSS; false`)

**Comment by manniL** [comment] 2019-04-05 14:15
Thanks for the report.

Duplicate of https://github.com/nuxt-community/style-resources-module/issues/35#issuecomment-465730212

Made this more clear in https://github.com/nuxt-community/style-resources-module/blob/master/README.md#setup

**Closed by manniL** 2019-04-05 14:15 UTC

**Comment by syffs** [comment] 2019-04-05 18:18
> Thanks for the report.
> 
> Duplicate of [#35 (comment)](https://github.com/nuxt-community/style-resources-module/issues/35#issuecomment-465730212)
> 
> Made this more clear in https://github.com/nuxt-community/style-resources-module/blob/master/README.md#setup

Thanks for the quick response !

Got it, only variables / mixins / functions ! Unfortunately, this means you can't use basic features such as `@include` or `@extend`...  

Is there no work around this ?

**Comment by manniL** [comment] 2019-04-05 19:36
I'm afraid no. You can still use placeholders for SASS and then use extend (I'd assume).
